# -*- coding: utf-8 -*-
"""generate_kpis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-MzA_f2wgYloC1TE920GadBc42FQkbp
"""

import pandas as pd
import numpy as np

from google.colab import files

print("Libraries imported successfully")

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)

print("Dataset loaded")
print("Shape:", df.shape)

df.head()

print("="*60)
print("DATASET INFORMATION")
print("="*60)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumn Names:")
for col in df.columns:
    print(col)

if "Country Name" in df.columns:
    df.rename(
        columns={"Country Name":"country_name"},
        inplace=True
    )

elif "Country" in df.columns:
    df.rename(
        columns={"Country":"country_name"},
        inplace=True
    )


print(df["country_name"].head())

required_columns = [
    "country_name",
    "power_index_rank_gap",
    "defense_budget_usd",
    "gdp_usd",
    "total_military_aircraft",
    "total_population",
    "continent",
    "region",
    "alliance"
]


missing=[]

for col in required_columns:
    if col not in df.columns:
        missing.append(col)


if len(missing)==0:
    print("All required columns available ✅")

else:
    print("Missing Columns:")
    print(missing)

if "power_index_rank_gap" not in df.columns:

    df["power_index_rank_gap"] = (
        df["rank"] - 1
    )


print(
df[
[
"country_name",
"power_index_rank_gap"
]
].head()
)

df["budget_to_gdp_ratio"] = (
    df["defense_budget_usd"] /
    df["gdp_usd"]
)


df[
[
"country_name",
"budget_to_gdp_ratio"
]
].head()

asset_columns = [
    "total_military_aircraft",
    "tanks",
    "total_naval_fleet"
]


available_assets=[]

for col in asset_columns:
    if col in df.columns:
        available_assets.append(col)


df["total_assets"] = (
    df[available_assets]
    .fillna(0)
    .sum(axis=1)
)


df["assets_per_capita"] = (
    df["total_assets"] /
    df["total_population"]
)


df[
[
"country_name",
"assets_per_capita"
]
].head()

df["NATO_flag"] = np.where(
    df["alliance"]=="NATO",
    1,
    0
)


df[
[
"country_name",
"alliance",
"NATO_flag"
]
].head()

numeric_columns = df.select_dtypes(
    include=np.number
).columns


df[numeric_columns] = (
    df[numeric_columns]
    .fillna(0)
)


print(
"Total Missing Values:",
df.isnull().sum().sum()
)

wide_df = df.copy()

print(
"Wide Shape:",
wide_df.shape
)

wide_df.head()

id_columns = [
    "country_name",
    "continent",
    "region",
    "alliance"
]


value_columns = [
    col for col in df.columns
    if col not in id_columns
]


long_df = df.melt(
    id_vars=id_columns,
    value_vars=value_columns,
    var_name="metric",
    value_name="value"
)


print(
"Long Shape:",
long_df.shape
)


long_df.head()

print("="*60)
print("FINAL VALIDATION")
print("="*60)


print(
"Wide Dataset:",
wide_df.shape
)


print(
"Long Dataset:",
long_df.shape
)


print(
"\nDuplicate Countries:",
wide_df["country_name"].duplicated().sum()
)


print(
"\nMissing Values:",
wide_df.isnull().sum().sum()
)

output_file = "military_final.xlsx"


with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    wide_df.to_excel(
        writer,
        sheet_name="military_wide",
        index=False
    )

    long_df.to_excel(
        writer,
        sheet_name="military_long",
        index=False
    )


print(
"military_final.xlsx created successfully"
)

files.download(
    "military_final.xlsx"
)