# -*- coding: utf-8 -*-
"""generate_kpis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XgZpWPHsA46Sp1QCBImP8hK9eULHxh9
"""

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

df = pd.read_csv("military_cleaned.csv")

print("Dataset Loaded Successfully!")
print("Shape:", df.shape)

df.head()

print("="*60)
print("MODULE 3 - KPI DATASET INFORMATION")
print("="*60)

print("\nRows :", df.shape[0])
print("Columns :", df.shape[1])

print("\nMissing Values:")

print(df.isnull().sum()[df.isnull().sum() > 0])

print("\nData Types:\n")
print(df.dtypes.value_counts())

kpi_analysis = pd.DataFrame({

    "KPI": [
        "Assets per Capita",
        "Budget-to-GDP Ratio",
        "Power Index Rank Gap",
        "Combined Personnel",
        "Coalition Budget",
        "Force Readiness Index",
        "Air Superiority Index",
        "Logistics Index",
        "Superiority Index",
        "Coalition Score",
        "Power Advantage",
        "Budget Advantage"
    ],

    "Columns Used": [

        "total_military_aircraft, tanks, armored_fighting_vehicles, self_propelled_artillery, towed_artillery, rocket_projectors, total_naval_fleet, total_population",

        "defense_budget_usd, gdp_usd",

        "power_index_rank_gap",

        "active_personnel, reserve_personnel, paramilitary",

        "defense_budget_usd, alliance",

        "fit_for_service, total_population, active_personnel",

        "fighter_aircraft, attack_aircraft, total_military_aircraft",

        "total_serviceable_airports, railway_coverage_km, roadway_coverage_km, major_ports_and_terminals, total_merchant_marine_fleet",

        "Force Readiness Index, Air Superiority Index, Logistics Index",

        "alliance, coalition_budget",

        "superiority_index, coalition_score",

        "defense_budget_usd, coalition_budget"

    ]

})

print("="*70)
print("MODULE 3 - KPI ANALYSIS")
print("="*70)

display(kpi_analysis)

# ============================================================
# CELL 5 - ASSETS PER CAPITA
# ============================================================

df["total_military_assets"] = (

    df["total_military_aircraft"]

    + df["tanks"]

    + df["armored_fighting_vehicles"]

    + df["self_propelled_artillery"]

    + df["towed_artillery"]

    + df["rocket_projectors"]

    + df["total_naval_fleet"]

)

df["assets_per_capita"] = (

    df["total_military_assets"]

    / df["total_population"]

)

print("Assets per Capita calculated successfully!")

display(

    df[

        [

            "Country Name",

            "total_military_assets",

            "assets_per_capita"

        ]

    ].head()

)

df["budget_to_gdp_ratio"] = (
    df["defense_budget_usd"] / df["gdp_usd"]
) * 100

print("Budget-to-GDP Ratio calculated successfully!\n")

display(
    df[
        [
            "Country Name",
            "defense_budget_usd",
            "gdp_usd",
            "budget_to_gdp_ratio"
        ]
    ].head()
)

# CELL 7 - KPI VALIDATION


print("="*60)
print("MODULE 3 KPI VALIDATION")
print("="*60)

print("\nMissing Values:\n")

print(df[
    [
        "assets_per_capita",
        "budget_to_gdp_ratio"
    ]
].isnull().sum())

print("\nSummary Statistics:\n")

display(
    df[
        [
            "assets_per_capita",
            "budget_to_gdp_ratio"
        ]
    ].describe()
)

# CELL 8 - FINAL DATASET INFORMATION

print("="*60)
print("FINAL KPI DATASET")
print("="*60)

print("Rows    :", df.shape[0])
print("Columns :", df.shape[1])

new_columns = [
    "total_military_assets",
    "assets_per_capita",
    "budget_to_gdp_ratio"
]

print("\nNew KPI Columns Added:")

for col in new_columns:
    print("✓", col)

df.to_excel("military_final.xlsx", index=False)

print("="*60)
print("EXPORT SUCCESSFUL")
print("="*60)

print("File Name : military_final.xlsx")
print("Shape     :", df.shape)

from google.colab import files

files.download("military_final.xlsx")