{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "734bff4b-7bf8-45cc-b5d9-f8844325d42a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import pandas as pd\n",
    "import re\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "c88b9d97-5eae-45ad-99af-53ef81a3ba3b",
   "metadata": {},
   "outputs": [],
   "source": [
    "HEADERS = {\n",
    "    \"User-Agent\": \"Mozilla/5.0\"\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "54c94184-dbf3-400f-b9c9-9ef558bc1564",
   "metadata": {},
   "outputs": [],
   "source": [
    "BASE_URL = \"https://www.globalfirepower.com/countries-listing.php\"\n",
    "\n",
    "OTHER_SOURCES = {\n",
    "    'https://www.globalfirepower.com/total-population-by-country.php': 'total_population',\n",
    "    'https://www.globalfirepower.com/available-military-manpower.php': 'total_military_manpower',\n",
    "    'https://www.globalfirepower.com/manpower-fit-for-military-service.php': 'fit_for_service',\n",
    "    'https://www.globalfirepower.com/manpower-reaching-military-age-annually.php': 'population_reaching_military_age_annually',\n",
    "    'https://www.globalfirepower.com/active-military-manpower.php': 'active_personnel',\n",
    "    'https://www.globalfirepower.com/active-reserve-military-manpower.php': 'reserve_personnel',\n",
    "    'https://www.globalfirepower.com/manpower-paramilitary.php': 'paramilitary',\n",
    "    'https://www.globalfirepower.com/aircraft-total.php': 'total_military_aircraft',\n",
    "    'https://www.globalfirepower.com/aircraft-total-fighters.php': 'fighter_aircraft',\n",
    "    'https://www.globalfirepower.com/aircraft-total-attack-types.php': 'attack_aircraft',\n",
    "    'https://www.globalfirepower.com/aircraft-total-transports.php': 'transport_aircraft',\n",
    "    'https://www.globalfirepower.com/aircraft-total-trainers.php': 'trainer_aircraft',\n",
    "    'https://www.globalfirepower.com/aircraft-total-special-mission.php': 'special_mission_aircraft',\n",
    "    'https://www.globalfirepower.com/aircraft-total-tanker-fleet.php': 'tanker_aircraft',\n",
    "    'https://www.globalfirepower.com/aircraft-helicopters-total.php': 'total_military_helicopters',\n",
    "    'https://www.globalfirepower.com/aircraft-helicopters-attack.php': 'attack_helicopters',\n",
    "    'https://www.globalfirepower.com/armor-tanks-total.php': 'tanks',\n",
    "    'https://www.globalfirepower.com/armor-apc-total.php': 'armored_fighting_vehicles',\n",
    "    'https://www.globalfirepower.com/armor-self-propelled-guns-total.php': 'self_propelled_artillery',\n",
    "    'https://www.globalfirepower.com/armor-towed-artillery-total.php': 'towed_artillery',\n",
    "    'https://www.globalfirepower.com/armor-mlrs-total.php': 'rocket_projectors',\n",
    "    'https://www.globalfirepower.com/navy-ships.php': 'total_naval_fleet',\n",
    "    'https://www.globalfirepower.com/navy-force-by-tonnage.php': 'total_naval_fleet_tonnage_mt',\n",
    "    'https://www.globalfirepower.com/navy-aircraft-carriers.php': 'aircraft_carriers',\n",
    "    'https://www.globalfirepower.com/navy-helo-carriers.php': 'helicopter_carriers',\n",
    "    'https://www.globalfirepower.com/navy-submarines.php': 'submarines',\n",
    "    'https://www.globalfirepower.com/navy-destroyers.php': 'destroyers',\n",
    "    'https://www.globalfirepower.com/navy-frigates.php': 'frigates',\n",
    "    'https://www.globalfirepower.com/navy-corvettes.php': 'corvettes',\n",
    "    'https://www.globalfirepower.com/navy-patrol-coastal-craft.php': 'coastal_patrol_craft',\n",
    "    'https://www.globalfirepower.com/navy-mine-warfare-craft.php': 'mine_warfare_craft',\n",
    "    'https://www.globalfirepower.com/defense-spending-budget.php': 'defense_budget_usd',\n",
    "    'https://www.globalfirepower.com/external-debt-by-country.php': 'external_debt_usd',\n",
    "    'https://www.globalfirepower.com/purchasing-power-parity.php': 'purchasing_power_parity_usd',\n",
    "    'https://www.globalfirepower.com/reserves-of-foreign-exchange-and-gold.php': 'foreign_exchange_and_gold_reserves_usd',\n",
    "    'https://www.globalfirepower.com/major-serviceable-airports-by-country.php': 'total_serviceable_airports',\n",
    "    'https://www.globalfirepower.com/labor-force-by-country.php': 'labour_force',\n",
    "    'https://www.globalfirepower.com/major-ports-and-terminals.php': 'major_ports_and_terminals',\n",
    "    'https://www.globalfirepower.com/merchant-marine-strength-by-country.php': 'total_merchant_marine_fleet',\n",
    "    'https://www.globalfirepower.com/railway-coverage.php': 'railway_coverage_km',\n",
    "    'https://www.globalfirepower.com/roadway-coverage.php': 'roadway_coverage_km',\n",
    "    'https://www.globalfirepower.com/oil-production-by-country.php': 'oil_production_bbl',\n",
    "    'https://www.globalfirepower.com/oil-consumption-by-country.php': 'oil_consumption_bbl',\n",
    "    'https://www.globalfirepower.com/proven-oil-reserves-by-country.php': 'proven_oil_reserves_bbl',\n",
    "    'https://www.globalfirepower.com/natural-gas-production-by-country.php': 'natural_gas_production_cum',\n",
    "    'https://www.globalfirepower.com/natural-gas-consumption-by-country.php': 'natural_gas_consumption_cum',\n",
    "    'https://www.globalfirepower.com/proven-natural-gas-reserves-by-country.php': 'proven_natural_gas_reserves_cum',\n",
    "    'https://www.globalfirepower.com/coal-production-by-country.php': 'coal_production_cum',\n",
    "    'https://www.globalfirepower.com/coal-consumption-by-country.php': 'coal_consumption_mt',\n",
    "    'https://www.globalfirepower.com/proven-coal-reserves-by-country.php': 'proven_coal_reserves_cum',\n",
    "    'https://www.globalfirepower.com/square-land-area.php': 'total_land_area_sq_km',\n",
    "    'https://www.globalfirepower.com/coastline-coverage.php': 'coastline_coverage_km',\n",
    "    'https://www.globalfirepower.com/border-coverage.php': 'border_coverage_km',\n",
    "    'https://www.globalfirepower.com/waterway-coverage.php': 'waterway_coverage_km'\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "39315378-fd23-4984-8f0c-7c9b8112b5f9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Scraping -> total_population\n",
      "Scraping -> total_military_manpower\n",
      "Scraping -> fit_for_service\n",
      "Scraping -> population_reaching_military_age_annually\n",
      "Scraping -> active_personnel\n",
      "Scraping -> reserve_personnel\n",
      "Scraping -> paramilitary\n",
      "Scraping -> total_military_aircraft\n",
      "Scraping -> fighter_aircraft\n",
      "Scraping -> attack_aircraft\n",
      "Scraping -> transport_aircraft\n",
      "Scraping -> trainer_aircraft\n",
      "Scraping -> special_mission_aircraft\n",
      "Scraping -> tanker_aircraft\n",
      "Scraping -> total_military_helicopters\n",
      "Scraping -> attack_helicopters\n",
      "Scraping -> tanks\n",
      "Scraping -> armored_fighting_vehicles\n",
      "Scraping -> self_propelled_artillery\n",
      "Scraping -> towed_artillery\n",
      "Scraping -> rocket_projectors\n",
      "Scraping -> total_naval_fleet\n",
      "Scraping -> total_naval_fleet_tonnage_mt\n",
      "Scraping -> aircraft_carriers\n",
      "Scraping -> helicopter_carriers\n",
      "Scraping -> submarines\n",
      "Scraping -> destroyers\n",
      "Scraping -> frigates\n",
      "Scraping -> corvettes\n",
      "Scraping -> coastal_patrol_craft\n",
      "Scraping -> mine_warfare_craft\n",
      "Scraping -> defense_budget_usd\n",
      "Scraping -> external_debt_usd\n",
      "Scraping -> purchasing_power_parity_usd\n",
      "Scraping -> foreign_exchange_and_gold_reserves_usd\n",
      "Scraping -> total_serviceable_airports\n",
      "Scraping -> labour_force\n",
      "Scraping -> major_ports_and_terminals\n",
      "Scraping -> total_merchant_marine_fleet\n",
      "Scraping -> railway_coverage_km\n",
      "Scraping -> roadway_coverage_km\n",
      "Scraping -> oil_production_bbl\n",
      "Scraping -> oil_consumption_bbl\n",
      "Scraping -> proven_oil_reserves_bbl\n",
      "Scraping -> natural_gas_production_cum\n",
      "Scraping -> natural_gas_consumption_cum\n",
      "Scraping -> proven_natural_gas_reserves_cum\n",
      "Scraping -> coal_production_cum\n",
      "Scraping -> coal_consumption_mt\n",
      "Scraping -> proven_coal_reserves_cum\n",
      "Scraping -> total_land_area_sq_km\n",
      "Scraping -> coastline_coverage_km\n",
      "Scraping -> border_coverage_km\n",
      "Scraping -> waterway_coverage_km\n"
     ]
    }
   ],
   "source": [
    "def scrape_page(url, column_name):\n",
    "    \"\"\"\n",
    "    Scrapes military and related statistics for all countries from a Global Firepower\n",
    "    ranking page and returns the extracted data as a pandas DataFrame.\n",
    "\n",
    "    The function sends an HTTP GET request to the provided URL, parses the HTML\n",
    "    content using BeautifulSoup, extracts each country's name and its corresponding\n",
    "    metric value from the page's `recordsetContainer` elements, and stores the\n",
    "    results in a DataFrame.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    url : str\n",
    "        The URL of the Global Firepower page containing the ranking data.\n",
    "\n",
    "    column_name : str\n",
    "        The name of the metric to be used as the column header in the returned\n",
    "        DataFrame (e.g., 'total_population', 'fighter_aircraft').\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    pandas.DataFrame\n",
    "        A DataFrame with two columns:\n",
    "        - 'country' : Name of the country.\n",
    "        - column_name : Corresponding metric value extracted from the page.\n",
    "\n",
    "    Notes\n",
    "    -----\n",
    "    - Assumes that each country's data is contained within a\n",
    "      `recordsetContainer` HTML element.\n",
    "    - Country names are extracted from the `longFormName` element, with\n",
    "      `shortFormName` used as a fallback if necessary.\n",
    "    - The returned DataFrame can be merged with other DataFrames on the\n",
    "      'country' column to create a consolidated dataset.\n",
    "    \"\"\"\n",
    "    print(f\"Scraping -> {column_name}\")\n",
    "\n",
    "    response = requests.get(url, headers=HEADERS)\n",
    "    soup = BeautifulSoup(response.text, \"html.parser\")\n",
    "\n",
    "    cards = soup.find_all(\"div\", class_=\"recordsetContainer\")\n",
    "\n",
    "    rows = []\n",
    "\n",
    "    for card in cards:\n",
    "\n",
    "        country = \"\"\n",
    "\n",
    "        long_name = card.find(\"div\", class_=\"longFormName\")\n",
    "        if long_name:\n",
    "            country = long_name.get_text(\" \", strip=True)\n",
    "\n",
    "        if not country:\n",
    "            short_name = card.find(\"div\", class_=\"shortFormName\")\n",
    "            if short_name:\n",
    "                country = short_name.get_text(\" \", strip=True)\n",
    "\n",
    "        value = \"\"\n",
    "\n",
    "        value_div = card.find(\"div\", class_=\"valueContainer\")\n",
    "        if value_div:\n",
    "            value = value_div.get_text(\" \", strip=True)\n",
    "\n",
    "        rows.append([country, value])\n",
    "\n",
    "    df = pd.DataFrame(rows, columns=[\"country\", column_name])\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "master_df = None\n",
    "\n",
    "for url, column in OTHER_SOURCES.items():\n",
    "\n",
    "    df = scrape_page(url, column)\n",
    "\n",
    "    if master_df is None:\n",
    "        master_df = df\n",
    "    else:\n",
    "        master_df = master_df.merge(df, on=\"country\", how=\"outer\")\n",
    "\n",
    "    time.sleep(1)\n",
    "\n",
    "master_df.to_csv(\"military_raw_data.csv\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "62240363-1b9d-4b55-b62f-48f15ef36aae",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "       country total_population total_military_manpower fit_for_service  \\\n",
      "0  Afghanistan       40,121,552              15,647,405       8,826,741   \n",
      "1      Albania        3,107,100               1,522,479       1,292,554   \n",
      "2      Algeria       47,022,473              22,570,787      19,185,169   \n",
      "3       Angola       37,202,061               7,440,412       3,720,206   \n",
      "4    Argentina       46,994,384              20,677,529      17,575,900   \n",
      "\n",
      "  population_reaching_military_age_annually active_personnel  \\\n",
      "0                                   842,553           75,000   \n",
      "1                                    62,142            7,500   \n",
      "2                                   752,360          130,000   \n",
      "3                                   372,021          107,000   \n",
      "4                                   704,916          108,000   \n",
      "\n",
      "  reserve_personnel paramilitary total_military_aircraft fighter_aircraft  \\\n",
      "0                 0       90,000                       5                0   \n",
      "1                 0          500                      20                0   \n",
      "2           150,000      150,000                     620              111   \n",
      "3                 0       10,000                     278               67   \n",
      "4            12,370       20,000                     241               23   \n",
      "\n",
      "   ...                         natural_gas_production_cum  \\\n",
      "0  ...  80,200,000                        \\t\\t\\t\\t\\t\\t...   \n",
      "1  ...  50,623,000                        \\t\\t\\t\\t\\t\\t...   \n",
      "2  ...  100,726,000,000                        \\t\\t\\t\\...   \n",
      "3  ...  5,514,000,000                        \\t\\t\\t\\t\\...   \n",
      "4  ...  43,280,000,000                        \\t\\t\\t\\t...   \n",
      "\n",
      "                         natural_gas_consumption_cum  \\\n",
      "0  80,200,000                        \\t\\t\\t\\t\\t\\t...   \n",
      "1  50,623,000                        \\t\\t\\t\\t\\t\\t...   \n",
      "2  47,963,000,000                        \\t\\t\\t\\t...   \n",
      "3  1,397,000,000                        \\t\\t\\t\\t\\...   \n",
      "4  46,228,000,000                        \\t\\t\\t\\t...   \n",
      "\n",
      "                     proven_natural_gas_reserves_cum  \\\n",
      "0  49,554,000,000                        \\t\\t\\t\\t...   \n",
      "1  5,692,000,000                        \\t\\t\\t\\t\\...   \n",
      "2  4,504,000,000,000                        \\t\\t\\...   \n",
      "3  343,002,000,000                        \\t\\t\\t\\...   \n",
      "4  396,464,000,000                        \\t\\t\\t\\...   \n",
      "\n",
      "                                 coal_production_cum  \\\n",
      "0  767,000                        \\t\\t\\t\\t\\t\\t\\r\\...   \n",
      "1  473,000                        \\t\\t\\t\\t\\t\\t\\r\\...   \n",
      "2  0                        \\t\\t\\t\\t\\t\\t\\r\\n\\t\\t\\...   \n",
      "3  0                        \\t\\t\\t\\t\\t\\t\\r\\n\\t\\t\\...   \n",
      "4  869,000                        \\t\\t\\t\\t\\t\\t\\r\\...   \n",
      "\n",
      "                                 coal_consumption_mt  \\\n",
      "0  503,000                        \\t\\t\\t\\t\\t\\t\\r\\...   \n",
      "1  255,000                        \\t\\t\\t\\t\\t\\t\\r\\...   \n",
      "2  3,000                        \\t\\t\\t\\t\\t\\t\\r\\n\\...   \n",
      "3  0                        \\t\\t\\t\\t\\t\\t\\r\\n\\t\\t\\...   \n",
      "4  2,534,000                        \\t\\t\\t\\t\\t\\t\\...   \n",
      "\n",
      "                            proven_coal_reserves_cum  \\\n",
      "0  66,000,000                        \\t\\t\\t\\t\\t\\t...   \n",
      "1  522,000,000                        \\t\\t\\t\\t\\t\\...   \n",
      "2  233,000,000                        \\t\\t\\t\\t\\t\\...   \n",
      "3  0                        \\t\\t\\t\\t\\t\\t\\r\\n\\t\\t\\...   \n",
      "4  799,999,000                        \\t\\t\\t\\t\\t\\...   \n",
      "\n",
      "                               total_land_area_sq_km  \\\n",
      "0  652,230                        \\t\\t\\t\\t\\t\\t\\r\\...   \n",
      "1  28,748                        \\t\\t\\t\\t\\t\\t\\r\\n...   \n",
      "2  2,381,740                        \\t\\t\\t\\t\\t\\t\\...   \n",
      "3  1,246,700                        \\t\\t\\t\\t\\t\\t\\...   \n",
      "4  2,780,400                        \\t\\t\\t\\t\\t\\t\\...   \n",
      "\n",
      "                               coastline_coverage_km  \\\n",
      "0  0                        \\t\\t\\t\\t\\t\\t\\r\\n\\t\\t\\...   \n",
      "1  362                        \\t\\t\\t\\t\\t\\t\\r\\n\\t\\...   \n",
      "2  998                        \\t\\t\\t\\t\\t\\t\\r\\n\\t\\...   \n",
      "3  1,600                        \\t\\t\\t\\t\\t\\t\\r\\n\\...   \n",
      "4  4,989                        \\t\\t\\t\\t\\t\\t\\r\\n\\...   \n",
      "\n",
      "                                  border_coverage_km  \\\n",
      "0  5,987                        \\t\\t\\t\\t\\t\\t\\r\\n\\...   \n",
      "1  691                        \\t\\t\\t\\t\\t\\t\\r\\n\\t\\...   \n",
      "2  6,734                        \\t\\t\\t\\t\\t\\t\\r\\n\\...   \n",
      "3  5,369                        \\t\\t\\t\\t\\t\\t\\r\\n\\...   \n",
      "4  11,968                        \\t\\t\\t\\t\\t\\t\\r\\n...   \n",
      "\n",
      "                                waterway_coverage_km  \n",
      "0  1,200                        \\t\\t\\t\\t\\t\\t\\r\\n\\...  \n",
      "1  41                        \\t\\t\\t\\t\\t\\t\\r\\n\\t\\t...  \n",
      "2  0                        \\t\\t\\t\\t\\t\\t\\r\\n\\t\\t\\...  \n",
      "3  1,300                        \\t\\t\\t\\t\\t\\t\\r\\n\\...  \n",
      "4  11,000                        \\t\\t\\t\\t\\t\\t\\r\\n...  \n",
      "\n",
      "[5 rows x 55 columns]\n"
     ]
    }
   ],
   "source": [
    "print(master_df.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "89aadbe8-372b-4750-8df0-572cbb6d5bed",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(145, 55)\n"
     ]
    }
   ],
   "source": [
    "print(master_df.shape)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
