# -*- coding: utf-8 -*-
"""scrape_military_metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xUW1QY3bw94swu5nWq3u_PlNo_1ORSSR
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

url = "https://www.globalfirepower.com/aircraft-total.php"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",
    "Referer": "https://www.google.com/",
    "Cache-Control": "max-age=0"
}

session = requests.Session()

response = session.get(
    url,
    headers=headers,
    timeout=60
)

print("Status Code :", response.status_code)

print("\nFirst 500 characters:\n")

print(response.text[:500])

html = response.text

soup = BeautifulSoup(html, "html.parser")

print("Page Title:")
print(soup.title.text)

rows = soup.find_all("div", class_="topRow")

print("\nTotal Rows Found:", len(rows))

data = []

for row in rows:

    country_div = row.find("div", class_="countryNameContainer")
    value_div = row.find("div", class_="valueContainer")

    if country_div and value_div:

        country = country_div.get_text(" ", strip=True)

        country = country.replace("\n", " ")

        country = " ".join(country.split())

        country = country.split()[0] if False else country

        value = value_div.get_text(" ", strip=True)

        value = value.replace(",", "")

        data.append([country, value])

print("Total Records:", len(data))

print("\nFirst 10 Records:\n")

for i in range(10):
    print(data[i])

df = pd.DataFrame(data, columns=["Country Name", "Total Aircraft"])

print(df.head(20))

def scrape_metric(url, column_name):

    print("=" * 60)
    print("Scraping:", column_name)
    print("=" * 60)

    session = requests.Session()

    response = session.get(
        url,
        headers=headers,
        timeout=60
    )

    print("Status Code:", response.status_code)

    if response.status_code != 200:
        print("Skipping...")
        return None

    soup = BeautifulSoup(response.text, "html.parser")

    rows = soup.find_all("div", class_="topRow")

    print("Rows Found:", len(rows))

    data = []

    for row in rows:

        country_div = row.find("div", class_="countryNameContainer")
        value_div = row.find("div", class_="valueContainer")

        if country_div is None or value_div is None:
            continue

        long_name = country_div.find("div", class_="longFormName")

        if long_name:
            country = long_name.get_text(strip=True)
        else:
            country = country_div.get_text(" ", strip=True)

        value = value_div.get_text(" ", strip=True)

        value = value.replace(",", "")
        value = value.strip()

        data.append([country, value])

    df = pd.DataFrame(
        data,
        columns=["Country Name", column_name]
    )

    print(df.head())

    return df

aircraft_df = scrape_metric(
    "https://www.globalfirepower.com/aircraft-total.php",
    "total_military_aircraft"
)

aircraft_df.head(10)

session = requests.Session()

def scrape_metric(url, column_name):

    print("=" * 70)
    print("Scraping :", column_name)
    print("URL :", url)

    response = session.get(
        url,
        headers=headers,
        timeout=60
    )

    print("Status Code :", response.status_code)

    if response.status_code != 200:
        print("Skipping this page...")
        return None

    soup = BeautifulSoup(response.text, "html.parser")

    rows = soup.find_all("div", class_="topRow")

    print("Rows Found :", len(rows))

    data = []

    for row in rows:

        country_div = row.find("div", class_="countryNameContainer")
        value_div = row.find("div", class_="valueContainer")

        if country_div is None or value_div is None:
            continue

        long_name = country_div.find("div", class_="longFormName")

        if long_name:
            country = long_name.get_text(strip=True)
        else:
            country = country_div.get_text(" ", strip=True)

        value = value_div.get_text(" ", strip=True)

        value = value.replace(",", "")
        value = value.strip()

        data.append([country, value])

    df = pd.DataFrame(
        data,
        columns=[
            "Country Name",
            column_name
        ]
    )

    print("Records Collected :", len(df))

    return df

OTHER_SOURCES = {

    "https://www.globalfirepower.com/total-population-by-country.php": "total_population",
    "https://www.globalfirepower.com/available-military-manpower.php": "total_military_manpower",
    "https://www.globalfirepower.com/manpower-fit-for-military-service.php": "fit_for_service",
    "https://www.globalfirepower.com/manpower-reaching-military-age-annually.php": "population_reaching_military_age_annually",
    "https://www.globalfirepower.com/active-military-manpower.php": "active_personnel",
    "https://www.globalfirepower.com/active-reserve-military-manpower.php": "reserve_personnel",
    "https://www.globalfirepower.com/manpower-paramilitary.php": "paramilitary",
    "https://www.globalfirepower.com/aircraft-total.php": "total_military_aircraft",
    "https://www.globalfirepower.com/aircraft-total-fighters.php": "fighter_aircraft",
    "https://www.globalfirepower.com/aircraft-total-attack-types.php": "attack_aircraft",
    "https://www.globalfirepower.com/aircraft-total-transports.php": "transport_aircraft",
    "https://www.globalfirepower.com/aircraft-total-trainers.php": "trainer_aircraft",
    "https://www.globalfirepower.com/aircraft-total-special-mission.php": "special_mission_aircraft",
    "https://www.globalfirepower.com/aircraft-total-tanker-fleet.php": "tanker_aircraft",
    "https://www.globalfirepower.com/aircraft-helicopters-total.php": "total_military_helicopters",
    "https://www.globalfirepower.com/aircraft-helicopters-attack.php": "attack_helicopters",
    "https://www.globalfirepower.com/armor-tanks-total.php": "tanks",
    "https://www.globalfirepower.com/armor-apc-total.php": "armored_fighting_vehicles",
    "https://www.globalfirepower.com/armor-self-propelled-guns-total.php": "self_propelled_artillery",
    "https://www.globalfirepower.com/armor-towed-artillery-total.php": "towed_artillery",
    "https://www.globalfirepower.com/armor-mlrs-total.php": "rocket_projectors",
    "https://www.globalfirepower.com/navy-ships.php": "total_naval_fleet",
    "https://www.globalfirepower.com/navy-force-by-tonnage.php": "total_naval_fleet_tonnage_mt",
    "https://www.globalfirepower.com/navy-aircraft-carriers.php": "aircraft_carriers",
    "https://www.globalfirepower.com/navy-helo-carriers.php": "helicopter_carriers",
    "https://www.globalfirepower.com/navy-submarines.php": "submarines",
    "https://www.globalfirepower.com/navy-destroyers.php": "destroyers",
    "https://www.globalfirepower.com/navy-frigates.php": "frigates",
    "https://www.globalfirepower.com/navy-corvettes.php": "corvettes",
    "https://www.globalfirepower.com/navy-patrol-coastal-craft.php": "coastal_patrol_craft",
    "https://www.globalfirepower.com/navy-mine-warfare-craft.php": "mine_warfare_craft",
    "https://www.globalfirepower.com/defense-spending-budget.php": "defense_budget_usd",
    "https://www.globalfirepower.com/external-debt-by-country.php": "external_debt_usd",
    "https://www.globalfirepower.com/purchasing-power-parity.php": "purchasing_power_parity_usd",
    "https://www.globalfirepower.com/reserves-of-foreign-exchange-and-gold.php": "foreign_exchange_and_gold_reserves_usd",
    "https://www.globalfirepower.com/major-serviceable-airports-by-country.php": "total_serviceable_airports",
    "https://www.globalfirepower.com/labor-force-by-country.php": "labour_force",
    "https://www.globalfirepower.com/major-ports-and-terminals.php": "major_ports_and_terminals",
    "https://www.globalfirepower.com/merchant-marine-strength-by-country.php": "total_merchant_marine_fleet",
    "https://www.globalfirepower.com/railway-coverage.php": "railway_coverage_km",
    "https://www.globalfirepower.com/roadway-coverage.php": "roadway_coverage_km",
    "https://www.globalfirepower.com/oil-production-by-country.php": "oil_production_bbl",
    "https://www.globalfirepower.com/oil-consumption-by-country.php": "oil_consumption_bbl",
    "https://www.globalfirepower.com/proven-oil-reserves-by-country.php": "proven_oil_reserves_bbl",
    "https://www.globalfirepower.com/natural-gas-production-by-country.php": "natural_gas_production_cum",
    "https://www.globalfirepower.com/natural-gas-consumption-by-country.php": "natural_gas_consumption_cum",
    "https://www.globalfirepower.com/proven-natural-gas-reserves-by-country.php": "proven_natural_gas_reserves_cum",
    "https://www.globalfirepower.com/coal-production-by-country.php": "coal_production_cum",
    "https://www.globalfirepower.com/coal-consumption-by-country.php": "coal_consumption_mt",
    "https://www.globalfirepower.com/proven-coal-reserves-by-country.php": "proven_coal_reserves_cum",
    "https://www.globalfirepower.com/square-land-area.php": "total_land_area_sq_km",
    "https://www.globalfirepower.com/coastline-coverage.php": "coastline_coverage_km",
    "https://www.globalfirepower.com/border-coverage.php": "border_coverage_km",
    "https://www.globalfirepower.com/waterway-coverage.php": "waterway_coverage_km"

}

import time

master_df = None

total_urls = len(OTHER_SOURCES)

current = 1

print("=" * 80)
print("STARTING COMPLETE MILITARY DATA SCRAPING")
print("=" * 80)

for url, column_name in OTHER_SOURCES.items():

    print("\n")
    print("=" * 80)
    print(f"[{current}/{total_urls}]")
    print("Column :", column_name)
    print("=" * 80)

    try:

        temp_df = scrape_metric(
            url,
            column_name
        )

        if temp_df is None:

            print("No data returned.")
            current += 1
            time.sleep(2)
            continue

        if master_df is None:

            master_df = temp_df.copy()

        else:

            master_df = pd.merge(

                master_df,

                temp_df,

                on="Country Name",

                how="outer"

            )

        print("Current Dataset Shape :")
        print(master_df.shape)

    except Exception as error:

        print("ERROR OCCURRED")
        print(error)

    current += 1

    print("Waiting for 2 seconds...")

    time.sleep(2)

print("\n")
print("=" * 80)
print("SCRAPING FINISHED")
print("=" * 80)

print("\n")

print(master_df.head())

print("\n")

print("Final Dataset Shape :")

print(master_df.shape)

master_df.to_csv(
    "military_raw_data.csv",
    index=False,
    encoding="utf-8"
)

print("========================================")
print("Raw Dataset Saved Successfully!")
print("File Name : military_raw_data.csv")
print("========================================")

from google.colab import files

files.download("military_raw_data.csv")

print("=" * 60)
print("DATASET INFORMATION")
print("=" * 60)

print("\nShape of Dataset:")
print(master_df.shape)

print("\n")

print("Column Names:")
for column in master_df.columns:
    print(column)

print("\n")

print("First 10 Rows:")
print(master_df.head(10))

print("\n")

print("Last 10 Rows:")
print(master_df.tail(10))

print("\n")

print("Missing Values:")
print(master_df.isnull().sum())

print("\n")

print("Duplicate Country Names:")
print(master_df["Country Name"].duplicated().sum())

print(master_df.shape)

!cp /continents2.csv /content/
!cp /gdp_data.csv /content/
!cp /NATO_1_Country_Stats.csv /content/

!ls /content

import pandas as pd

continent_df = pd.read_csv("continents2.csv")
gdp_df = pd.read_csv("gdp_data.csv")
nato_df = pd.read_csv("NATO_1_Country_Stats.csv")

print("Datasets Loaded Successfully!")

continent_df = continent_df[["name", "region", "sub-region"]]

continent_df.rename(columns={
    "name":"Country Name",
    "region":"continent",
    "sub-region":"region"
}, inplace=True)

gdp_df = gdp_df.sort_values("year")

gdp_df = gdp_df.groupby("country_name").tail(1)

gdp_df = gdp_df[["country_name","value"]]

gdp_df.rename(columns={
    "country_name":"Country Name",
    "value":"gdp_usd"
}, inplace=True)

nato_df = nato_df[["Country"]].drop_duplicates()

nato_df.rename(columns={
    "Country":"Country Name"
}, inplace=True)

nato_df["alliance"] = "NATO"

mapping = {

"United States of America":"United States",
"Russian Federation":"Russia",
"Iran (Islamic Republic of)":"Iran",
"Syrian Arab Republic":"Syria",
"Viet Nam":"Vietnam",
"Lao People's Democratic Republic":"Laos",
"Republic of Moldova":"Moldova",
"Venezuela (Bolivarian Republic of)":"Venezuela",
"Bolivia (Plurinational State of)":"Bolivia",
"United Republic of Tanzania":"Tanzania",
"Czechia":"Czech Republic",
"Türkiye":"Turkey",
"Korea, Republic of":"South Korea",
"Korea, Democratic People's Republic of":"North Korea",
"Belize":"Beliz"

}

continent_df["Country Name"] = continent_df["Country Name"].replace(mapping)

gdp_df["Country Name"] = gdp_df["Country Name"].replace(mapping)

nato_df["Country Name"] = nato_df["Country Name"].replace(mapping)

continent_df = continent_df.drop_duplicates(subset=["Country Name"])

gdp_df = gdp_df.drop_duplicates(subset=["Country Name"])

nato_df = nato_df.drop_duplicates(subset=["Country Name"])

print(continent_df.shape)

print(continent_df.shape)

master_df = master_df.merge(
    continent_df,
    on="Country Name",
    how="left"
)

print("Shape:", master_df.shape)
print("Missing Continent:", master_df["continent"].isnull().sum())
print("Missing Region:", master_df["region"].isnull().sum())

print(master_df.columns.tolist())

master_df = master_df.drop(columns=[
    "continent_x",
    "region_x",
    "continent_y",
    "region_y"
])

print(master_df.columns.tolist())
print(master_df.shape)

missing = master_df[master_df["continent"].isna()]

print("Missing Countries:", len(missing))
print()

for country in sorted(missing["Country Name"].tolist()):
    print(country)

continent_df["Country Name"] = continent_df["Country Name"].replace({

    "Beliz": "Belize",
    "Bosnia Herzegovina": "Bosnia and Herzegovina",
    "Czech Republic": "Czechia",
    "Ivory Coast": "Côte d'Ivoire",
    "Congo (Kinshasa)": "Democratic Republic of the Congo",
    "Congo (Brazzaville)": "Republic of the Congo",
    "North Korea": "Korea, Democratic People's Republic of",
    "South Korea": "Korea, Republic of",
    "Macedonia": "North Macedonia",
    "Turkey": "Turkiye"

})

continent_df = continent_df.drop_duplicates(subset=["Country Name"])

master_df = master_df.drop(columns=["continent", "region"])

master_df = master_df.merge(
    continent_df,
    on="Country Name",
    how="left"
)

print("Shape:", master_df.shape)
print("Missing Continent:", master_df["continent"].isna().sum())
print("Missing Region:", master_df["region"].isna().sum())

missing = master_df[master_df["continent"].isna()]

print("Missing Countries:")
for country in sorted(missing["Country Name"].tolist()):
    print(country)

countries_to_check = [
    "Bosnia and Herzegovina",
    "Côte d'Ivoire",
    "Democratic Republic of the Congo",
    "Korea, Democratic People's Republic of",
    "Kosovo",
    "Republic of the Congo"
]

for c in countries_to_check:
    print("\n==============================")
    print(c)
    print("==============================")
    print(
        continent_df[
            continent_df["Country Name"].str.contains(
                c.split()[0], case=False, na=False
            )
        ]
    )

continent_df["Country Name"] = continent_df["Country Name"].replace({

    "Bosnia And Herzegovina": "Bosnia and Herzegovina",
    "Côte D'Ivoire": "Côte d'Ivoire",
    "Congo (Democratic Republic Of The)": "Democratic Republic of the Congo"

})

master_df = master_df.drop(columns=["continent","region"])

master_df = master_df.merge(
    continent_df,
    on="Country Name",
    how="left"
)

master_df.loc[
    master_df["Country Name"]=="Korea, Democratic People's Republic of",
    ["continent","region"]
] = ["Asia","Eastern Asia"]

master_df.loc[
    master_df["Country Name"]=="Republic of the Congo",
    ["continent","region"]
] = ["Africa","Sub-Saharan Africa"]

master_df.loc[
    master_df["Country Name"]=="Kosovo",
    ["continent","region"]
] = ["Europe","Southern Europe"]

print(master_df["continent"].isna().sum())
print(master_df["region"].isna().sum())
print(master_df.shape)

# Merge GDP Data

master_df = master_df.merge(
    gdp_df,
    on="Country Name",
    how="left"
)

print("GDP merged successfully!")

print("Shape:", master_df.shape)

print("Missing GDP:", master_df["gdp_usd"].isnull().sum())

missing_gdp = master_df[master_df["gdp_usd"].isna()]

print("Missing GDP Countries:", len(missing_gdp))
print()

for country in sorted(missing_gdp["Country Name"].tolist()):
    print(country)

gdp_df["Country Name"] = gdp_df["Country Name"].replace({

    "Egypt, Arab Rep.": "Egypt",
    "Iran, Islamic Rep.": "Iran",
    "Kyrgyz Republic": "Kyrgyzstan",
    "Lao PDR": "Laos",
    "Slovak Republic": "Slovakia",
    "Venezuela, RB": "Venezuela",
    "Yemen, Rep.": "Yemen",
    "Congo, Dem. Rep.": "Democratic Republic of the Congo",
    "Congo, Rep.": "Republic of the Congo",
    "Korea, Dem. People's Rep.": "Korea, Democratic People's Republic of",
    "Korea, Rep.": "Korea, Republic of",
    "Czech Republic": "Czechia",
    "Egypt, Arab Republic": "Egypt",
    "Iran (Islamic Republic of)": "Iran"

})

gdp_df = gdp_df.drop_duplicates(subset=["Country Name"])

master_df = master_df.drop(columns=["gdp_usd"])

master_df = master_df.merge(
    gdp_df,
    on="Country Name",
    how="left"
)

print("Shape:", master_df.shape)
print("Missing GDP:", master_df["gdp_usd"].isna().sum())

missing_gdp = master_df[master_df["gdp_usd"].isna()]

print("Remaining Missing GDP Countries:")
for country in sorted(missing_gdp["Country Name"].tolist()):
    print(country)

countries = ["Bel", "Cote", "Korea", "Taiwan"]

for word in countries:
    print(f"\n===== {word} =====")
    print(
        gdp_df[gdp_df["Country Name"].str.contains(word, case=False, na=False)]["Country Name"].unique()
    )

gdp_df["Country Name"] = gdp_df["Country Name"].replace({

    "Beliz": "Belize",
    "Cote d'Ivoire": "Côte d'Ivoire"

})

gdp_df = gdp_df.drop_duplicates(subset=["Country Name"])

master_df = master_df.drop(columns=["gdp_usd"])

master_df = master_df.merge(
    gdp_df,
    on="Country Name",
    how="left"
)

print("Missing GDP:", master_df["gdp_usd"].isna().sum())

print(master_df[master_df["gdp_usd"].isna()][["Country Name"]])

master_df.loc[
    master_df["Country Name"] == "Taiwan",
    "gdp_usd"
] = 790000000000

master_df.loc[
    master_df["Country Name"] == "Korea, Democratic People's Republic of",
    "gdp_usd"
] = 18000000000

print("Missing GDP:", master_df["gdp_usd"].isna().sum())

print(nato_df.columns.tolist())

master_df = master_df.merge(
    nato_df,
    on="Country Name",
    how="left"
)

master_df["alliance"] = master_df["alliance"].fillna("Non-NATO")

print("Shape:", master_df.shape)
print()
print(master_df["alliance"].value_counts())

import numpy as np

derived_columns = [
    "power_index_rank_gap",
    "force_readiness_index",
    "air_superiority_index",
    "logistics_index",
    "superiority_index",
    "coalition_score",
    "coalition_budget",
    "combined_personnel",
    "power_advantage",
    "budget_advantage"
]

for col in derived_columns:
    master_df[col] = np.nan

print("Derived columns added successfully!")

print("Shape:", master_df.shape)

print("="*60)
print("MODULE 1 FINAL DATASET")
print("="*60)

print("\nShape:", master_df.shape)

print("\nMissing Continent:", master_df["continent"].isna().sum())
print("Missing Region:", master_df["region"].isna().sum())
print("Missing GDP:", master_df["gdp_usd"].isna().sum())
print("Missing Alliance:", master_df["alliance"].isna().sum())

print("\nDuplicate Countries:",
      master_df["Country Name"].duplicated().sum())

print("\nTotal Columns:", len(master_df.columns))

master_df.to_csv("military_raw_data.csv", index=False)

print("✅ military_raw_data.csv saved successfully!")

from google.colab import files

# Save the final Module 1 deliverable
master_df.to_csv("military_raw_data.csv", index=False)

# Download it to your computer
files.download("military_raw_data.csv")