{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 180,
   "id": "35d1af4c-20f6-4cb4-a709-98546b752b8a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 181,
   "id": "4083fada-5f57-43b2-8c5f-a75a9a07a63a",
   "metadata": {},
   "outputs": [],
   "source": [
    "gdp = pd.read_csv(r\"C:\\Users\\devin\\Downloads\\gdp_data.csv\")\n",
    "meta = pd.read_csv(r\"C:\\Users\\devin\\Downloads\\country_codes.csv\")\n",
    "military = pd.read_csv(r\"C:\\Users\\devin\\Unified-Military-Analytics\\military_cleaned.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 182,
   "id": "2ef9b023-2dfb-4bc6-818a-2d6a7d77abdf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "GDP\n",
      "(13365, 4)\n",
      "['country_name', 'country_code', 'year', 'value']\n",
      "  country_name country_code  year        value\n",
      "0  Afghanistan          AFG  1960  537777811.1\n",
      "1  Afghanistan          AFG  1961  548888895.6\n",
      "2  Afghanistan          AFG  1962  546666677.8\n",
      "3  Afghanistan          AFG  1963  751111191.1\n",
      "4  Afghanistan          AFG  1964  800000044.4\n",
      "\n",
      "\n",
      "Metadata\n",
      "(217, 3)\n",
      "['country_code', 'region', 'income_group']\n",
      "  country_code                     region         income_group\n",
      "0          ABW  Latin America & Caribbean          High income\n",
      "1          AFG                 South Asia           Low income\n",
      "2          AGO         Sub-Saharan Africa  Lower middle income\n",
      "3          ALB      Europe & Central Asia  Upper middle income\n",
      "4          AND      Europe & Central Asia          High income\n",
      "\n",
      "\\Military\n",
      "(145, 57)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>country</th>\n",
       "      <th>global_firepower_rank</th>\n",
       "      <th>power_index</th>\n",
       "      <th>total_population</th>\n",
       "      <th>total_military_manpower</th>\n",
       "      <th>fit_for_service</th>\n",
       "      <th>population_reaching_military_age_annually</th>\n",
       "      <th>active_personnel</th>\n",
       "      <th>reserve_personnel</th>\n",
       "      <th>paramilitary</th>\n",
       "      <th>...</th>\n",
       "      <th>natural_gas_production_cum</th>\n",
       "      <th>natural_gas_consumption_cum</th>\n",
       "      <th>proven_natural_gas_reserves_cum</th>\n",
       "      <th>coal_production_cum</th>\n",
       "      <th>coal_consumption_mt</th>\n",
       "      <th>proven_coal_reserves_cum</th>\n",
       "      <th>total_land_area_sq_km</th>\n",
       "      <th>coastline_coverage_km</th>\n",
       "      <th>border_coverage_km</th>\n",
       "      <th>waterway_coverage_km</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Afghanistan</td>\n",
       "      <td>121</td>\n",
       "      <td>2.7342</td>\n",
       "      <td>40121552</td>\n",
       "      <td>15647405</td>\n",
       "      <td>8826741</td>\n",
       "      <td>842553</td>\n",
       "      <td>75000</td>\n",
       "      <td>0</td>\n",
       "      <td>90000</td>\n",
       "      <td>...</td>\n",
       "      <td>80200000</td>\n",
       "      <td>80200000</td>\n",
       "      <td>49554000000</td>\n",
       "      <td>767000</td>\n",
       "      <td>503000</td>\n",
       "      <td>66000000</td>\n",
       "      <td>652230</td>\n",
       "      <td>0</td>\n",
       "      <td>5987</td>\n",
       "      <td>1200</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Albania</td>\n",
       "      <td>77</td>\n",
       "      <td>1.7258</td>\n",
       "      <td>3107100</td>\n",
       "      <td>1522479</td>\n",
       "      <td>1292554</td>\n",
       "      <td>62142</td>\n",
       "      <td>7500</td>\n",
       "      <td>0</td>\n",
       "      <td>500</td>\n",
       "      <td>...</td>\n",
       "      <td>50623000</td>\n",
       "      <td>50623000</td>\n",
       "      <td>5692000000</td>\n",
       "      <td>473000</td>\n",
       "      <td>255000</td>\n",
       "      <td>522000000</td>\n",
       "      <td>28748</td>\n",
       "      <td>362</td>\n",
       "      <td>691</td>\n",
       "      <td>41</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Algeria</td>\n",
       "      <td>27</td>\n",
       "      <td>0.4849</td>\n",
       "      <td>47022473</td>\n",
       "      <td>22570787</td>\n",
       "      <td>19185169</td>\n",
       "      <td>752360</td>\n",
       "      <td>130000</td>\n",
       "      <td>150000</td>\n",
       "      <td>150000</td>\n",
       "      <td>...</td>\n",
       "      <td>100726000000</td>\n",
       "      <td>47963000000</td>\n",
       "      <td>4504000000000</td>\n",
       "      <td>0</td>\n",
       "      <td>3000</td>\n",
       "      <td>233000000</td>\n",
       "      <td>2381740</td>\n",
       "      <td>998</td>\n",
       "      <td>6734</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Angola</td>\n",
       "      <td>59</td>\n",
       "      <td>1.1045</td>\n",
       "      <td>37202061</td>\n",
       "      <td>7440412</td>\n",
       "      <td>3720206</td>\n",
       "      <td>372021</td>\n",
       "      <td>107000</td>\n",
       "      <td>0</td>\n",
       "      <td>10000</td>\n",
       "      <td>...</td>\n",
       "      <td>5514000000</td>\n",
       "      <td>1397000000</td>\n",
       "      <td>343002000000</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1246700</td>\n",
       "      <td>1600</td>\n",
       "      <td>5369</td>\n",
       "      <td>1300</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Argentina</td>\n",
       "      <td>32</td>\n",
       "      <td>0.5983</td>\n",
       "      <td>46994384</td>\n",
       "      <td>20677529</td>\n",
       "      <td>17575900</td>\n",
       "      <td>704916</td>\n",
       "      <td>108000</td>\n",
       "      <td>12370</td>\n",
       "      <td>20000</td>\n",
       "      <td>...</td>\n",
       "      <td>43280000000</td>\n",
       "      <td>46228000000</td>\n",
       "      <td>396464000000</td>\n",
       "      <td>869000</td>\n",
       "      <td>2534000</td>\n",
       "      <td>799999000</td>\n",
       "      <td>2780400</td>\n",
       "      <td>4989</td>\n",
       "      <td>11968</td>\n",
       "      <td>11000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 57 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       country  global_firepower_rank  power_index  total_population  \\\n",
       "0  Afghanistan                    121       2.7342          40121552   \n",
       "1      Albania                     77       1.7258           3107100   \n",
       "2      Algeria                     27       0.4849          47022473   \n",
       "3       Angola                     59       1.1045          37202061   \n",
       "4    Argentina                     32       0.5983          46994384   \n",
       "\n",
       "   total_military_manpower  fit_for_service  \\\n",
       "0                 15647405          8826741   \n",
       "1                  1522479          1292554   \n",
       "2                 22570787         19185169   \n",
       "3                  7440412          3720206   \n",
       "4                 20677529         17575900   \n",
       "\n",
       "   population_reaching_military_age_annually  active_personnel  \\\n",
       "0                                     842553             75000   \n",
       "1                                      62142              7500   \n",
       "2                                     752360            130000   \n",
       "3                                     372021            107000   \n",
       "4                                     704916            108000   \n",
       "\n",
       "   reserve_personnel  paramilitary  ...  natural_gas_production_cum  \\\n",
       "0                  0         90000  ...                    80200000   \n",
       "1                  0           500  ...                    50623000   \n",
       "2             150000        150000  ...                100726000000   \n",
       "3                  0         10000  ...                  5514000000   \n",
       "4              12370         20000  ...                 43280000000   \n",
       "\n",
       "   natural_gas_consumption_cum  proven_natural_gas_reserves_cum  \\\n",
       "0                     80200000                      49554000000   \n",
       "1                     50623000                       5692000000   \n",
       "2                  47963000000                    4504000000000   \n",
       "3                   1397000000                     343002000000   \n",
       "4                  46228000000                     396464000000   \n",
       "\n",
       "   coal_production_cum  coal_consumption_mt  proven_coal_reserves_cum  \\\n",
       "0               767000               503000                  66000000   \n",
       "1               473000               255000                 522000000   \n",
       "2                    0                 3000                 233000000   \n",
       "3                    0                    0                         0   \n",
       "4               869000              2534000                 799999000   \n",
       "\n",
       "   total_land_area_sq_km  coastline_coverage_km  border_coverage_km  \\\n",
       "0                 652230                      0                5987   \n",
       "1                  28748                    362                 691   \n",
       "2                2381740                    998                6734   \n",
       "3                1246700                   1600                5369   \n",
       "4                2780400                   4989               11968   \n",
       "\n",
       "   waterway_coverage_km  \n",
       "0                  1200  \n",
       "1                    41  \n",
       "2                     0  \n",
       "3                  1300  \n",
       "4                 11000  \n",
       "\n",
       "[5 rows x 57 columns]"
      ]
     },
     "execution_count": 182,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "print(\"GDP\")\n",
    "print(gdp.shape)\n",
    "print(gdp.columns.tolist())\n",
    "print(gdp.head())\n",
    "\n",
    "print(\"\\n\\nMetadata\")\n",
    "print(meta.shape)\n",
    "print(meta.columns.tolist())\n",
    "print(meta.head())\n",
    "\n",
    "print(\"\\n\\Military\")\n",
    "print(military.shape)\n",
    "military.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 183,
   "id": "acbaeccd-27c7-46ca-ae8f-7d74474b1dbe",
   "metadata": {},
   "outputs": [],
   "source": [
    "gdp = gdp.rename(\n",
    "    columns={\n",
    "        \"country_name\": \"country\",\n",
    "        \"value\": \"gdp_usd\"\n",
    "    }\n",
    ")\n",
    "\n",
    "gdp = (\n",
    "    gdp.sort_values(\"year\")\n",
    "       .groupby(\"country\", as_index=False)\n",
    "       .last()\n",
    ")\n",
    "\n",
    "gdp = gdp[\n",
    "    [\n",
    "        \"country\",\n",
    "        \"country_code\",\n",
    "        \"gdp_usd\"\n",
    "    ]\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 184,
   "id": "8b64878d-d138-4df8-bf60-535ec6e92646",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(262, 5)\n"
     ]
    }
   ],
   "source": [
    "gdp = gdp.merge(\n",
    "    meta,\n",
    "    on=\"country_code\",\n",
    "    how=\"left\"\n",
    ")\n",
    "\n",
    "print(gdp.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 185,
   "id": "4ed20f64-21b4-4a71-9a86-ef0136185553",
   "metadata": {},
   "outputs": [],
   "source": [
    "mapping = {\n",
    "    \"Egypt, Arab Rep.\":\"Egypt\",\n",
    "    \"Iran, Islamic Rep.\":\"Iran\",\n",
    "    \"Russian Federation\":\"Russia\",\n",
    "    \"Korea, Dem. People's Rep.\":\"North Korea\",\n",
    "    \"Korea, Rep.\":\"South Korea\",\n",
    "    \"Turkiye\":\"Turkey\",\n",
    "    \"Lao PDR\":\"Laos\",\n",
    "    \"Kyrgyz Republic\":\"Kyrgyzstan\",\n",
    "    \"Slovak Republic\":\"Slovakia\",\n",
    "    \"Venezuela, RB\":\"Venezuela\",\n",
    "    \"Yemen, Rep.\":\"Yemen\",\n",
    "    \"Syrian Arab Republic\":\"Syria\",\n",
    "    \"Congo, Dem. Rep.\":\"Democratic Republic of the Congo\",\n",
    "    \"Congo, Rep.\":\"Republic of the Congo\",\n",
    "    \"Taiwan, China\":\"Taiwan\",\n",
    "    \"Cote d'Ivoire\":\"Ivory Coast\"\n",
    "}\n",
    "\n",
    "gdp[\"country\"] = gdp[\"country\"].replace(mapping)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 186,
   "id": "a7bbd391-efc8-426e-9fa8-b0a0d74d3260",
   "metadata": {},
   "outputs": [],
   "source": [
    "military[\"country\"] = military[\"country\"].replace({\n",
    "    \"Beliz\": \"Belize\",\n",
    "    \"Turkiye\": \"Turkey\"\n",
    "})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 187,
   "id": "1da6339a-1141-4fc2-ab08-956fb5f91d09",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(145, 61)\n",
      "       country  global_firepower_rank  power_index  total_population  \\\n",
      "0  Afghanistan                    121       2.7342          40121552   \n",
      "1      Albania                     77       1.7258           3107100   \n",
      "2      Algeria                     27       0.4849          47022473   \n",
      "3       Angola                     59       1.1045          37202061   \n",
      "4    Argentina                     32       0.5983          46994384   \n",
      "\n",
      "   total_military_manpower  fit_for_service  \\\n",
      "0                 15647405          8826741   \n",
      "1                  1522479          1292554   \n",
      "2                 22570787         19185169   \n",
      "3                  7440412          3720206   \n",
      "4                 20677529         17575900   \n",
      "\n",
      "   population_reaching_military_age_annually  active_personnel  \\\n",
      "0                                     842553             75000   \n",
      "1                                      62142              7500   \n",
      "2                                     752360            130000   \n",
      "3                                     372021            107000   \n",
      "4                                     704916            108000   \n",
      "\n",
      "   reserve_personnel  paramilitary  ...  coal_consumption_mt  \\\n",
      "0                  0         90000  ...               503000   \n",
      "1                  0           500  ...               255000   \n",
      "2             150000        150000  ...                 3000   \n",
      "3                  0         10000  ...                    0   \n",
      "4              12370         20000  ...              2534000   \n",
      "\n",
      "   proven_coal_reserves_cum  total_land_area_sq_km  coastline_coverage_km  \\\n",
      "0                  66000000                 652230                      0   \n",
      "1                 522000000                  28748                    362   \n",
      "2                 233000000                2381740                    998   \n",
      "3                         0                1246700                   1600   \n",
      "4                 799999000                2780400                   4989   \n",
      "\n",
      "   border_coverage_km  waterway_coverage_km  country_code       gdp_usd  \\\n",
      "0                5987                  1200           AFG  1.458314e+10   \n",
      "1                 691                    41           ALB  1.888210e+10   \n",
      "2                6734                     0           DZA  1.920000e+11   \n",
      "3                5369                  1300           AGO  1.070000e+11   \n",
      "4               11968                 11000           ARG  6.330000e+11   \n",
      "\n",
      "                       region         income_group  \n",
      "0                  South Asia           Low income  \n",
      "1       Europe & Central Asia  Upper middle income  \n",
      "2  Middle East & North Africa  Lower middle income  \n",
      "3          Sub-Saharan Africa  Lower middle income  \n",
      "4   Latin America & Caribbean  Upper middle income  \n",
      "\n",
      "[5 rows x 61 columns]\n"
     ]
    }
   ],
   "source": [
    "df = military.merge(\n",
    "    gdp,\n",
    "    on=\"country\",\n",
    "    how=\"left\"\n",
    ")\n",
    "\n",
    "print(df.shape)\n",
    "print(df.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 188,
   "id": "dd09740a-5768-4537-89fe-8cd6d17575d7",
   "metadata": {},
   "outputs": [],
   "source": [
    "continent_map = {\n",
    "    \"East Asia & Pacific\": \"Asia\",\n",
    "    \"Europe & Central Asia\": \"Europe\",\n",
    "    \"Latin America & Caribbean\": \"North America\",\n",
    "    \"Middle East & North Africa\": \"Asia\",\n",
    "    \"North America\": \"North America\",\n",
    "    \"South Asia\": \"Asia\",\n",
    "    \"Sub-Saharan Africa\": \"Africa\"\n",
    "}\n",
    "\n",
    "df[\"continent\"] = df[\"region\"].map(continent_map)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 189,
   "id": "cf630431-423d-441e-ae58-7dd2ae57cf2d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['North Korea', 'Taiwan']\n"
     ]
    }
   ],
   "source": [
    "print(df[df[\"gdp_usd\"].isna()][\"country\"].tolist())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 190,
   "id": "59ca5c7c-ef90-41b9-90e5-4d58cb2940de",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Series([], Name: country, dtype: object)\n",
      "123    South Korea\n",
      "Name: country, dtype: object\n"
     ]
    }
   ],
   "source": [
    "print(gdp[gdp[\"country\"].str.contains(\"Tai\", case=False, na=False)][\"country\"])\n",
    "\n",
    "print(gdp[gdp[\"country\"].str.contains(\"Korea\", case=False, na=False)][\"country\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 191,
   "id": "fd80fa8f-cc17-4c5c-8a61-aebb3a6fba4c",
   "metadata": {},
   "outputs": [],
   "source": [
    "gdp = gdp.drop_duplicates(subset=\"country\", keep=\"first\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "caec3ef3-4f4f-4914-bc71-de4ad9a209c0",
   "metadata": {},
   "source": [
    "## KPI Engineering"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 192,
   "id": "09cf4799-048b-461d-b086-2c572b1c3e55",
   "metadata": {},
   "outputs": [],
   "source": [
    "df[\"gdp_rank\"] = (\n",
    "    df[\"gdp_usd\"]\n",
    "    .rank(method=\"dense\", ascending=False)\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 193,
   "id": "16a2f285-1cf9-4b83-b2ef-e1a8112c46c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "asset_cols = [\n",
    "    \"tanks\",\n",
    "    \"armored_fighting_vehicles\",\n",
    "    \"self_propelled_artillery\",\n",
    "    \"towed_artillery\",\n",
    "    \"rocket_projectors\",\n",
    "    \"fighter_aircraft\",\n",
    "    \"attack_aircraft\",\n",
    "    \"transport_aircraft\",\n",
    "    \"trainer_aircraft\",\n",
    "    \"special_mission_aircraft\",\n",
    "    \"tanker_aircraft\",\n",
    "    \"attack_helicopters\",\n",
    "    \"submarines\",\n",
    "    \"destroyers\",\n",
    "    \"frigates\",\n",
    "    \"corvettes\",\n",
    "    \"aircraft_carriers\",\n",
    "    \"helicopter_carriers\"\n",
    "]\n",
    "\n",
    "df[\"total_assets\"] = df[asset_cols].fillna(0).sum(axis=1)\n",
    "\n",
    "df[\"assets_per_capita\"] = (\n",
    "    df[\"total_assets\"] /\n",
    "    df[\"total_population\"]\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 194,
   "id": "4e4afbad-f526-4d97-9bae-5ec1421d4b24",
   "metadata": {},
   "outputs": [],
   "source": [
    "df[\"budget_to_gdp_ratio\"] = (\n",
    "    df[\"defense_budget_usd\"] /\n",
    "    df[\"gdp_usd\"]\n",
    ") * 100"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 195,
   "id": "a53cca58-99bb-4763-a03b-9d650fb3264d",
   "metadata": {},
   "outputs": [],
   "source": [
    "df[\"power_index_rank_gap\"] = (\n",
    "    df[\"gdp_rank\"] -\n",
    "    df[\"global_firepower_rank\"]\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 196,
   "id": "15da7312-fb5b-4300-aefe-170a3019ede9",
   "metadata": {},
   "outputs": [],
   "source": [
    "nato = {\n",
    "    \"Albania\",\"Belgium\",\"Bulgaria\",\"Canada\",\"Croatia\",\n",
    "    \"Czech Republic\",\"Denmark\",\"Estonia\",\"Finland\",\n",
    "    \"France\",\"Germany\",\"Greece\",\"Hungary\",\"Iceland\",\n",
    "    \"Italy\",\"Latvia\",\"Lithuania\",\"Luxembourg\",\n",
    "    \"Montenegro\",\"Netherlands\",\"North Macedonia\",\n",
    "    \"Norway\",\"Poland\",\"Portugal\",\"Romania\",\n",
    "    \"Slovakia\",\"Slovenia\",\"Spain\",\"Sweden\",\n",
    "    \"Turkey\",\"United Kingdom\",\"United States\"\n",
    "}\n",
    "\n",
    "df[\"is_nato\"] = df[\"country\"].isin(nato)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 197,
   "id": "b00b0a48-ad1b-4194-bf59-b0206132aca4",
   "metadata": {},
   "outputs": [],
   "source": [
    "id_columns = [\n",
    "    \"country\",\n",
    "    \"country_code\",\n",
    "    \"region\",\n",
    "    \"continent\",\n",
    "    \"income_group\",\n",
    "    \"is_nato\"\n",
    "]\n",
    "\n",
    "long_df = df.melt(\n",
    "    id_vars=id_columns,\n",
    "    var_name=\"metric\",\n",
    "    value_name=\"value\"\n",
    ")\n",
    "\n",
    "long_df.to_excel(\n",
    "    r\"C:\\Users\\devin\\Unified-Military-Analytics\\military_long.xlsx\",\n",
    "    index=False\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 198,
   "id": "a470ef51-3bfc-4be5-ac2a-ff113a18f1cf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Module 3 Completed Successfully!\n",
      "(145, 68)\n",
      "\n",
      "Missing Percentage\n",
      "power_index_rank_gap    1.37931\n",
      "country_code            1.37931\n",
      "region                  1.37931\n",
      "gdp_usd                 1.37931\n",
      "budget_to_gdp_ratio     1.37931\n",
      "gdp_rank                1.37931\n",
      "continent               1.37931\n",
      "income_group            1.37931\n",
      "total_population        0.00000\n",
      "power_index             0.00000\n",
      "dtype: float64\n"
     ]
    }
   ],
   "source": [
    "df.to_excel(r\"C:\\Users\\devin\\Unified-Military-Analytics\\military_final.xlsx\",index=False)\n",
    "\n",
    "print(\"Module 3 Completed Successfully!\")\n",
    "print(df.shape)\n",
    "\n",
    "print(\"\\nMissing Percentage\")\n",
    "print(\n",
    "    (df.isna().mean()*100)\n",
    "    .sort_values(ascending=False)\n",
    "    .head(10)\n",
    ")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
